sudo: false
language: scala

scala:
  - 2.10.6
  - 2.11.8

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test scalastyle coverageReport

after_success: bash <(curl -s https://codecov.io/bash)
